kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "chuck-ui"
  namespace: "chuck-ops"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/chuck-ui"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "nodejs:latest"
        namespace: openshift
  output:
    to:
      kind: "ImageStreamTag"
      name: "chuck-ui:latest"
      namespace: "chuck"
