apiVersion: v1
kind: Service
metadata:
  name: "chuck-api"
  namespace: "chuck"
spec:
  selector:
    app: "chuck-api"
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30081
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  labels:
    app: "chuck-api"
  name: "chuck-api"
  namespace: "chuck"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "chuck-api"
    spec:
      containers:
      - name: "chuck-api"
        image: "dimssss/chuck-api:0.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod